defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
      sass:

style: compressed

exclude:
- package.json
- package-lock.json
- node_modules
- gulpfile.js
- assets/vendor
- README.md
- LICENSE

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]